import { SessionLanguageTexts } from './types';

export const sessionLanguageTexts: SessionLanguageTexts = {
  ar: {
    newSession: 'جلسة جديدة',
    patientInfo: 'معلومات المريض',
    patientName: 'اسم المريض',
    age: 'العمر',
    gender: 'الجنس',
    male: 'ذكر',
    female: 'أنثى',
    medicalRecordNumber: 'رقم السجل الطبي',
    phoneNumber: 'رقم الهاتف',
    allergies: 'الحساسيات',
    medications: 'الأدوية الحالية',
    medicalHistory: 'التاريخ المرضي',
    chiefComplaint: 'الشكوى الرئيسية',
    sessionNotes: 'ملاحظات الجلسة',
    addNote: 'إضافة ملاحظة',
    noteType: 'نوع الملاحظة',
    observation: 'ملاحظة',
    diagnosis: 'تشخيص',
    plan: 'خطة',
    general: 'عام',
    priority: 'الأولوية',
    low: 'منخفضة',
    medium: 'متوسطة',
    high: 'عالية',
    startSession: 'بدء الجلسة',
    continueToRecording: 'متابعة إلى التسجيل',
    editSession: 'تحرير الجلسة',
    deleteSession: 'حذف الجلسة',
    saveChanges: 'حفظ التغييرات',
    cancel: 'إلغاء',
    required: 'مطلوب',
    optional: 'اختياري',
    sessionSummary: 'ملخص الجلسة',
    notesCount: 'عدد الملاحظات',
    noNotes: 'لا توجد ملاحظات',
    addFirstNote: 'إضافة أول ملاحظة',
    recentSessions: 'الجلسات الأخيرة',
    noSessions: 'لا توجد جلسات',
    createFirstSession: 'إنشاء أول جلسة',
    deleteConfirm: 'هل أنت متأكد من حذف هذه الجلسة؟',
    deleteAllSessions: 'حذف جميع الجلسات',
    exportSession: 'تصدير الجلسة',
    importSession: 'استيراد جلسة',
    sessionId: 'معرف الجلسة',
    createdAt: 'تاريخ الإنشاء',
    lastAccessed: 'آخر وصول',
    sessionStatus: 'حالة الجلسة',
    active: 'نشطة',
    completed: 'مكتملة',
    paused: 'متوقفة',
    searchPlaceholder: 'البحث في الجلسات...',
    filterByStatus: 'تصفية حسب الحالة',
    all: 'الكل',
    sortBy: 'ترتيب حسب',
    name: 'الاسم',
    date: 'التاريخ',
    noteContent: 'محتوى الملاحظة',
    noteTypePlaceholder: 'اختر نوع الملاحظة...',
    priorityLevel: 'مستوى الأولوية',
    tags: 'العلامات',
    addTag: 'إضافة علامة',
    removeTag: 'إزالة علامة',
    deleteNote: 'حذف الملاحظة',
    editNote: 'تحرير الملاحظة',
    saveNote: 'حفظ الملاحظة',
    timestampLabel: 'الوقت',
    quickNotes: 'ملاحظات سريعة',
    templates: 'القوالب',
    useTemplate: 'استخدام القالب',
    createTemplate: 'إنشاء قالب جديد',
    manageTemplates: 'إدارة القوالب',
    customTemplates: 'القوالب المخصصة',
    systemTemplates: 'القوالب النظام',
    templateTitle: 'عنوان القالب',
    templateDescription: 'وصف القالب',
    templateContent: 'محتوى القالب',
    templateCategory: 'فئة القالب',
    saveTemplate: 'حفظ القالب',
    editTemplate: 'تعديل القالب',
    deleteTemplate: 'حذف القالب',
    confirmDeleteTemplate: 'هل تريد حذف هذا القالب؟',
    templateSaved: 'تم حفظ القالب بنجاح',
    templateDeleted: 'تم حذف القالب بنجاح',
    noCustomTemplates: 'لا توجد قوالب مخصصة',
    createFirstTemplate: 'إنشاء أول قالب مخصص',
    patientInfoComplete: 'معلومات المريض مكتملة',
    notesAdded: 'ملاحظة مضافة',
    readyToRecord: 'جاهز للتسجيل'
  },
  en: {
    newSession: 'New Session',
    patientInfo: 'Patient Information',
    patientName: 'Patient Name',
    age: 'Age',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    medicalRecordNumber: 'Medical Record Number',
    phoneNumber: 'Phone Number',
    allergies: 'Allergies',
    medications: 'Current Medications',
    medicalHistory: 'Medical History',
    chiefComplaint: 'Chief Complaint',
    sessionNotes: 'Session Notes',
    addNote: 'Add Note',
    noteType: 'Note Type',
    observation: 'Observation',
    diagnosis: 'Diagnosis',
    plan: 'Plan',
    general: 'General',
    priority: 'Priority',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    startSession: 'Start Session',
    continueToRecording: 'Continue to Recording',
    editSession: 'Edit Session',
    deleteSession: 'Delete Session',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    required: 'Required',
    optional: 'Optional',
    sessionSummary: 'Session Summary',
    notesCount: 'Notes Count',
    noNotes: 'No notes',
    addFirstNote: 'Add first note',
    recentSessions: 'Recent Sessions',
    noSessions: 'No sessions',
    createFirstSession: 'Create first session',
    deleteConfirm: 'Are you sure you want to delete this session?',
    deleteAllSessions: 'Delete All Sessions',
    exportSession: 'Export Session',
    importSession: 'Import Session',
    sessionId: 'Session ID',
    createdAt: 'Created At',
    lastAccessed: 'Last Accessed',
    sessionStatus: 'Session Status',
    active: 'Active',
    completed: 'Completed',
    paused: 'Paused',
    searchPlaceholder: 'Search sessions...',
    filterByStatus: 'Filter by status',
    all: 'All',
    sortBy: 'Sort by',
    name: 'Name',
    date: 'Date',
    noteContent: 'Note content',
    noteTypePlaceholder: 'Select note type...',
    priorityLevel: 'Priority level',
    tags: 'Tags',
    addTag: 'Add tag',
    removeTag: 'Remove tag',
    deleteNote: 'Delete note',
    editNote: 'Edit note',
    saveNote: 'Save note',
    timestampLabel: 'Time',
    quickNotes: 'Quick Notes',
    templates: 'Templates',
    useTemplate: 'Use Template',
    createTemplate: 'Create New Template',
    manageTemplates: 'Manage Templates',
    customTemplates: 'Custom Templates',
    systemTemplates: 'System Templates',
    templateTitle: 'Template Title',
    templateDescription: 'Template Description',
    templateContent: 'Template Content',
    templateCategory: 'Template Category',
    saveTemplate: 'Save Template',
    editTemplate: 'Edit Template',
    deleteTemplate: 'Delete Template',
    confirmDeleteTemplate: 'Are you sure you want to delete this template?',
    templateSaved: 'Template saved successfully',
    templateDeleted: 'Template deleted successfully',
    noCustomTemplates: 'No custom templates',
    createFirstTemplate: 'Create your first custom template',
    patientInfoComplete: 'Patient info complete',
    notesAdded: 'Notes added',
    readyToRecord: 'Ready to record'
  }
};

export const getSessionTexts = (language: 'ar' | 'en') => {
  return sessionLanguageTexts[language];
};
